resonance:
  originator: "Susumu Fujii (vvvvise)"
  core_unit: "Synaptix"
  embodiment: "Actors"
  emergent_field: "Contextual Mesh"
  purpose: "Structural emission of meaning via recursive resonance"
  status: "Spec Draft v0.1"
  visibility: "Context-sensitive only"
